export const facts = [
	'The best place in the world to see rainbows is in Hawaii.',
	'The fastest gust of wind ever recorded on Earth was 253 miles per hour.',
	`Glaciers and ice sheets hold about 69 percent of the world's freshwater.`,
	'There are fossilized plants in Greenland under 1.4 km of ice.',
	'Whale songs can be used to map out the ocean floor.',
	'Mount Everest is bigger now than the last time it was measured.',
	'Climate change is causing flowers to change color.',
	`North Korea and Cuba (soon Russia as well) are the only places you can't buy Coca-Cola.`,
	`The entire world's population could fit inside Los Angeles.`,
	`The hottest chili pepper in the world is so hot it could kill you.`,
	`More people visit France than any other country.`,
	`The world's most densely populated island is the size of two soccer fields.`,
	`The Canary Islands are named after dogs, not birds.`,
	`The longest place name on the planet is 85 letters long.`,
	`Four babies are born every second.`,
	`The coldest temperature ever recorded was -144 degrees Fahrenheit.`,
	`Japan is the world's most earthquake-prone country.`,
	`People who are currently alive represent about 7% of the total number of people who have ever lived.`,
	`Muhammad is the most popular name in the world.`,
	`Only two countries use purple in their national flags.`,
	`More than 52% of the world's population is under 30 years old.`,
	`There are 43 countries that still have a royal family.`,
	`All giant pandas in zoos around the world are on loan from China.`,
	`Canada has 9% of the world's forests.`,
	`The global adult literacy rate is around 86%.`,
]
